### ISSUE TITLE
Signatures/encryption

### ISSUE THREAD

**Issue by sp5wwp** [M17-Project/M17_spec#138]
1. Expand the definition of the encryption subtype subfield of `TYPE` with AES key length indication.
2. Add definitions for ECDSA signed streams.

**Comment by lwvmobile** [comment]
Something I was considering on that, is if we use the following setup for AES, it'll let us use the crypt code we've got currently and also allow compatibility to m17-tools which still uses the hard coded 128 keylen value, since that signals enc_subtype as 0 on AES, and is also the same progression of key len values that scrambler mode uses.

subtype 0 for AES 128;
subtype 1 for AES 192;
subtype 2 for AES 256;

**Comment by sp5wwp** [comment]
ECDSA added in [9ec7c6c](https://github.com/M17-Project/M17_spec/commit/9ec7c6cf323d6a4d46c5966768490b94fc422e77).

**Comment by sp5wwp** [comment]
Fix the frame numbering (for the frames carrying signature) to 0x7FFC, 0x7FFD, 0x7FFE, 0xFFFF.

**Comment by sp5wwp** [comment]
> Fix the frame numbering (for the frames carrying signature) to 0x7FFC, 0x7FFD, 0x7FFE, 0xFFFF.

Done in [f07d251](https://github.com/M17-Project/M17_spec/commit/f07d25159c911c1fbde34942ce9bcbc4befb0d4e).
