### ISSUE TITLE
GNSS fields in feet and miles? Really?

### ISSUE THREAD

**Issue by SmittyHalibut** [M17-Project/M17_spec#62]
I write this issue as an American, one of the very few countries yet to pull our heads from our asses wrt the metric system.

Why (in the hell) is the GNSS elevation provided in feet MSL, and speed in MPH?!

**Comment by g4klx** [comment]
I agree, however feet and MPH are was is output in your typical NMEA sentence, and are also the units used by APRS. As much as I dislike them, I don't see that it makes sense to change them to metric in order to convert them back again. One small advantage of using feet, is that they have finer grain than metres using just integers.

**Comment by SmittyHalibut** [comment]
Bah. Stupid Americans.

Yeah, alright. Being consistent is good, I agree.  Closing the issue.

**Comment by onemikedelta** [comment]
I don't know are there any specific messages however, I believe, most of messages are metric. Some sentences contain speed  km/h with knot which are still not miles.
MHP = 1609 meter ph
knot = 1852 meter ph
1 mile per hour (mph) = 0.868976242 knot (kn, kt or kts)
